### ISSUE TITLE
ImplicitlyWait don't work on appium 1.8 with UIautomator2

### ISSUE THREAD

**Issue by JasperJhons** [appium/appium-uiautomator2-server#170] opened 2018-06-07 11:38 UTC
When my test can't find element immediately and appium trying to waiting up for it then  server rise exception.
With previous versions of appium server or without uiautoamtor2 all works pretty good.

## Environment
**Appium 1.8.9**
**Appium-java-client 6.0.0**
**UIAutomator2 (1.12.0)**
**MacOS High Sierra 10.13.4 (17E199)**
**AVD**

## Appium logs
```Bash
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["xpath","//*[@text='Показывать Intro при каждом логине']","474b155f-9244-43f8-a32f-d18339dba82b"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 50000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8297/wd/hub/session/2fee2063-ea91-4a59-a64a-c4a4776b7047/element] with body: {"strategy":"xpath","selector":"//*[@text='Показывать Intro при каждом логине']","context":"","multiple":false}
[W3C] Encountered internal error running command:  {"w3cStatus":400,"jsonwp":{"sessionId":"2fee2063-ea91-4a59-a64a-c4a4776b7047","status":7,"value":"An element could not be located on the page using the given search parameters."}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"sessionId":"2fee2063-ea91-4a59-a64a-c4a4776b7047","status":7,"value":"An element could not be located on the page using the given search parameters."}
[W3C]     at JWProxy.proxy$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
```

# Driver caps
```Java
capabilities.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, true);
        capabilities.setCapability(AndroidMobileCapabilityType.UNICODE_KEYBOARD, true);
        capabilities.setCapability(AndroidMobileCapabilityType.RESET_KEYBOARD, true);
        capabilities.setCapability(AndroidMobileCapabilityType.APP_WAIT_ACTIVITY, appSettings.getPackageName() + appSettings.getStartPageId());
        capabilities.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES, true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        capabilities.setCapability(AndroidMobileCapabilityType.SYSTEM_PORT, driversSettings.getSystemPort());

DriversSettings.builder()
                .appiumRemoteUrl(appiumURL)
                .deviceName(props.getProperty(DEVICE_NAME))
                .UDID(props.getProperty(UDID))
                .filePath(props.getProperty(FILE_PATH))
                .implicitlyWaitInSeconds(50)
                .findingTimeOutInSeconds(50)
                .newCommandTimeoutInSeconds(50)
```

**Comment by mykola-mokhnach** [comment] 2018-06-07 11:40
Duplicate of https://github.com/appium/appium/issues/10809

**Closed by mykola-mokhnach** 2018-06-07 11:40 UTC
